const mongoose = require('mongoose')

const recipeSchema= new mongoose.Schema({
    recipeName:{
        type:String,
        required:true
    },
    recipeIngredients:{
        type:String,
        required:true
    },
    recipeOverView:{
        type:String,
        required:true
    },
    recipeDescription:{
        type:String,
        required:true
    },
    recipeLink:{
        type:String,
        required:true,
        unique:true
    },
    recipephoto:{
        type:String,
        required:true
    },
    recipecategory:{
        type:String,
        required:true
    },
    userId:{
        type:String,
        required:true
    },
    userName:{
        type:String,
        required:true
    },
    userProfilePic:{
        type:String,
        default:""
    },
    likes:{
        type:Number,
        default:0
    },
    dislikes:{
        type:Number,
        default:0
    },
    likedUsers:{
        type:[String],
        default:[]
    },
    dislikedUsers:{
        type:[String],
        default:[]
    }
})
const recipe = mongoose.model('recipe',recipeSchema)
module.exports=recipe